[devstack] End the sg-core process on unstack
In https://github.com/openstack-k8s-operators/sg-core/pull/22, sg-core
was updated to use the run_process devstack function to start the
process.
The corresponding function to stop the process was not included.
This causes issue when running devstack locally. It stacks the first
time, but after running unstack.sh, stack.sh fails with the following
error:

    Error: creating container storage: the container name "sg-core"
    is already in use by xxxxx. You have to remove that container.

Removing the container before running stack prevents this error.
The stop_process devstack function does this action.